---

- hosts: all
  tasks:
    - name: create a group of all hosts by operating system
      group_by:
        key: "{{ ansible_distribution}}-{{ ansible_distribution_major_version }}"


- hosts: CentOS-6
  tasks:
    - name: install initscripts
      package:
        name: initscripts
        state: present

- hosts: CentOS-7
  tasks:
    - name: remove requiretty from /etc/sudoers
      lineinfile:
        dest: "/etc/sudoers"
        regexp: "requiretty$"
        state: absent

- hosts: all
  any_errors_fatal: true
  roles:
    - role: inkatze.wildfly
