---

- hosts: wildfly-centos6
  tasks:
    - name: install initscripts
      package:
        name: initscripts
        state: present

- hosts: wildfly-centos7
  tasks:
    - name: remove requiretty from /etc/sudoers
      lineinfile:
        dest: "/etc/sudoers"
        regexp: "requiretty$"
        state: absent

- hosts: all
  vars:
    wildfly_remove_download_file: false
    wildfly_management_users:
      - { name: 'david', password: 'ruomlig' }
      - { name: 'roger', password: 'sretaw' }
    wildfly_app_users:
      - { name: 'rich', password: 'thgirw' }
      - { name: 'nick', password: 'nosam' }
  roles:
    - role: inkatze.wildfly
