---

- hosts: all
  tasks:
    - debug:
        msg: "System {{ inventory_hostname }} has OS {{ ansible_distribution}}-{{ ansible_distribution_major_version }}"

- hosts: all
  tasks:
    - name: create a group of all hosts by operating system
      group_by:
        key: "{{ ansible_distribution}}-{{ ansible_distribution_major_version }}"

# - hosts: CentOS-6
#   tasks:
#     - name: install initscripts
#       package:
#         name: initscripts
#         state: present

- hosts: CentOS-7
  tasks:
    - name: remove requiretty from /etc/sudoers
      lineinfile:
        dest: "/etc/sudoers"
        regexp: "requiretty$"
        state: absent

- hosts: all
  become: yes
  any_errors_fatal: true
  pre_tasks:
    - debug:
        msg: "wildfly_remove_download_file is {{ wildfly_remove_download_file }}"
    - debug:
        msg: "wildfly_version is {{ wildfly_version }}"
  roles:
#    - role: inkatze.wildfly
    - role: wildfly
