---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
    - name: wildfly-centos7-8.2.1
      image: milcom/centos7-systemd:latest
      privileged: True

    - name: wildfly-centos7-9.0.1
      image: milcom/centos7-systemd:latest
      privileged: True

    - name: wildfly-centos7-10.1.0
      image: milcom/centos7-systemd:latest
      privileged: True

    - name: wildfly-centos8-20.0.1
      image: centos:8
      command: /sbin/init
      tmpfs:
        - /run
        - /tmp
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  inventory:
    host_vars:
      wildfly-centos6-8.2.1:
        wildfly_version: 8.2.1.Final
        wildfly_custom_properties:
          wildfly_messaging_group_address: 231.7.7.9
        wildfly_custom_environment:
          SHUTDOWN_WAIT: 3
        wildfly_temp_dir: /tmp/wildfly_temp
      wildfly-centos6-9.0.1:
        wildfly_version: 9.0.1.Final
        wildfly_custom_properties:
          jboss.node.name: wildfly
        wildfly_custom_environment:
          SHUTDOWN_WAIT: 3
        wildfly_temp_dir: /tmp/wildfly_temp
      wildfly-centos6-10.1.0:
        wildfly_version: 10.1.0.Final
      wildfly-centos7-8.2.1:
        wildfly_version: 8.2.1.Final
      wildfly-centos7-9.0.1:
        wildfly_version: 9.0.1.Final
      wildfly-centos7-10.1.0:
        wildfly_version: 10.1.0.Final
      wildfly-centos8-20.0.1:
        ansible_user: ansible
        wildfly_version: 20.0.1.Final
    group_vars:
      all:
        wildfly_remove_download_file: False
        wildfly_management_users:
          - { name: 'david', password: 'ruomlig' }
          - { name: 'roger', password: 'sretaw' }
        wildfly_app_users:
          - { name: 'rich', password: 'thgirw' }
          - { name: 'nick', password: 'nosam' }
        wildfly_custom_properties:
          jboss.node.name: wildfly-group
        wildfly_custom_environment:
          STARTUP_WAIT: 2
          SHUTDOWN_WAIT: 2
        wildfly_temp_dir: /opt/wildfly/standalone/tmp

  lint: |
      set -e
      yamllint .
      ansible-lint

scenario:
  name: default
