---

- hosts: all
  tasks:
    - debug:
        msg: "System {{ inventory_hostname }} has OS {{ ansible_distribution}}-{{ ansible_distribution_major_version }}"

- hosts: all
  tasks:
    - name: create a group of all hosts by operating system
      group_by:
        key: "{{ ansible_distribution}}_{{ ansible_distribution_major_version }}"